import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Bevan } from 'next/font/google';
import { Providers } from "@/store/provider";

const bevan = Bevan({
  subsets: ['latin'],
  weight: ["400"],
  variable: '--font-bevan',
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" className={`${bevan.variable}`}>
        <body className={inter.className}>{children}</body>
      </html>
    </Providers>
  );
}

export default RootLayout;
